[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=xfce
allow-guest=false

[greeter]
background=/usr/share/backgrounds/kitpro-default.png
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
font-name=Sans 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
